# Generated by Django 4.0.3 on 2022-09-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hijo',
            old_name='padre',
            new_name='tutor',
        ),
        migrations.AddField(
            model_name='actividad',
            name='hijos',
            field=models.ManyToManyField(through='backend.HijoActividad', to='backend.hijo'),
        ),
    ]
