# Generated by Django 4.0.3 on 2022-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_padre_hijo_tutor_actividad_hijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
