# Generated by Django 4.0.3 on 2022-10-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_historiadelaactividad_name of constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
