# Generated by Django 4.0.3 on 2022-10-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_sugerencia_hijo_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hijo')),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('hijo', models.ManyToManyField(to='backend.hijo')),
            ],
        ),
    ]
