# Generated by Django 4.0.3 on 2022-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_actividad_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='logros',
            field=models.ManyToManyField(through='backend.LogroHijo', to='backend.logro'),
        ),
    ]
